{% set name = "pynemaiqpet" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pynemaiqpet-{{ version }}.tar.gz
  sha256: 6d32bb123968834b440b1dc73adcfac47846319e7e507bb90019d4db66b30517

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - pynemaiqpet_wb_nema_iq = pynemaiqpet.command_line_tools:wb_nema_iq

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - pymirc >=0.23,<1
    - nibabel >=3.0
    - matplotlib-base >=3.1
    - pydicom >=2.0,<3
    - scipy >=1.4
    - pandas >=1.0
    - lmfit >=1.0

test:
  imports:
    - pynemaiqpet
  commands:
    - pip check
    - pynemaiqpet_wb_nema_iq -h
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Analysis of PET NEMA IQ phantom scans
  license: MIT
  license_file: LICENSE
  home: https://github.com/gschramm/pynemaiqpet

extra:
  recipe-maintainers:
    - gschramm
